keycloak:
    auth-server-url: http://localhost:8080/auth
    bearer-only: true
    public-client: true
    realm: test-keycloak
    resource: demo-app
server:
    port: 8083
spring:
    datasource:
        password: Fuck1245!
        url: jdbc:mysql://localhost:3307/TEST_KEYCLOACK
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
