keycloak:
    auth-server-url: http://localhost:8080/auth
    bearer-only: true
    credentials:
        secret: afd9ee86-41bc-4215-b020-f81fcc544109
    public-client: true
    realm: test-keycloak
    resource: demo-app-be
    ssl-required: external
    use-resource-role-mappings: true
server:
    port: 8083
spring:
    datasource:
        password: Fuck1245!
        url: jdbc:mysql://localhost:3307/TEST_KEYCLOACK
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
